### ISSUE TITLE
'OpenAL Error: 40964' on Ubuntu 18.04

### ISSUE THREAD

**Issue by jmacato** [feliwir/SharpAudio#1]
Seems like it's failing when it's trying to get an audio device/sink @ `AlNative.alcOpenDevice(null)`.on ALEngine.cs

**Comment by feliwir** [comment]
This library is still somewhat WIP. Can you show your code? I didn't test on anything but Windows yet. Do you have libopenal installed?

**Comment by jmacato** [comment]
I've just ran the SharpAudio.Sample package out-of-the-box. I havent checked but i do think i have it installed since the dll checks would fail otherwise

**Comment by feliwir** [comment]
Sorry for the delay. I'll check this on my own Ubuntu machine and then check for the source of the problem.

**Comment by feliwir** [comment]
So i fixed the problem. The issue was that alGetError always throws an error on Ubuntu for some reason and i was always crashing the application in that case. I tested on on Ubuntu 18.04 and i can't spot any issues on Ubuntu 18.04 anymore. Please let me know if it works for you aswell!

**Comment by jmacato** [comment]
Thanks, there doesnt seem to be any OpenAL errors! although it fails to play some wav file that i give it to :(

**Comment by feliwir** [comment]
Hm, i only checked with the 2 files that are in the repository so far. (SharpAudio.Tests/Assets). The issue with wav files is that they support 20 different kind of compressions and i only support uncompressed (PCM) and ADPCM so far. Are you getting any errors?

**Comment by feliwir** [comment]
I created a new issue, let's take the discussion there
