### ISSUE TITLE
FFmpeg_Initialize() fails on Windows

### ISSUE THREAD

**Issue by dev-bre** [feliwir/SharpAudio#12]
Trying to read a mp3 file on Windows, the following exception gets raised:

Unable to load DLL 'avutil.56': The specified module could not be found.'

The mp3 gets played on Linux without issues.

**Comment by feliwir** [comment]
Can you please check the FOURCC of your file? It should have gone that path:
https://github.com/feliwir/SharpAudio/blob/0856c58267bc61ff732ad908db0ff9fedb7e1400/src/SharpAudio.Codec/SoundStream.cs#L87

So it's probably not a standard MP3

**Comment by feliwir** [comment]
I think this should be fixed in the current version. Can you please check with the latest NuGet @dev-bre  ?
