### ISSUE TITLE
AVutil.56 not found

### ISSUE THREAD

**Issue by PieroCastillo** [feliwir/SharpAudio#18]
Hello, For me this project is amazing, but I receive this error always:
```c#
D:\TestProjects\TestSharpAudio>dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'avutil.56': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_601(UInt64 size)
   at SharpAudio.Codec.FFmpeg.FFmpegDecoder.Ffmpeg_Initialize()
   at SharpAudio.Codec.FFmpeg.FFmpegDecoder..ctor(Stream src)
   at SharpAudio.Codec.SoundStream..ctor(Stream stream, SoundSink sink, Boolean autoDisposeSink)
   at SharpAudio.Codec.SoundStream..ctor(Stream stream, AudioEngine engine, Submixer mixer)
   at SharpAudio.Sample.Program.Main(String[] args) in D:\TestProjects\TestSharpAudio\Program.cs:line 15
```

this is the code:
```c#
        static void Main(string[] args)
        {
            var  engine = AudioEngine.CreateDefault();
            var  soundStream = new SoundStream(File.OpenRead("path"), engine); //in this is throw the error, this says "System.DllNotFoundException: Unable to load DLL 'avutil.56'"
            soundStream.Volume = 50f;
            Console.WriteLine("Loaded Correctly");
            soundStream.Play();
        }
```
Settongs:
- Windows 10 20H2
- Net 5.0

**Comment by feliwir** [comment]
Hey, FFMpeg is used when the file in question can't be opened with the builtin mp3 or wav decoder. What type of file are you trying to open? `File.OpenRead("path")` seems wrong

**Comment by PieroCastillo** [comment]
It's an mp3 file

**Comment by feliwir** [comment]
Yes, then it's probably a file that cannot be loaded by the builtin mp3 decoder, so you need to provide FFMpeg binaries which can. I'll not describe the process how to build FFMpeg on windows here.

**Comment by PieroCastillo** [comment]
> Yes, then it's probably a file that cannot be loaded by the builtin mp3 decoder, so you need to provide FFMpeg binaries which can. I'll not describe the process how to build FFMpeg on windows here.

mmm, if the file is an mp3, why the builtin mp3 decoder cannot decode it?

**Comment by PieroCastillo** [comment]
> Yes, then it's probably a file that cannot be loaded by the builtin mp3 decoder, so you need to provide FFMpeg binaries which can. I'll not describe the process how to build FFMpeg on windows here.

I've installed ffmpeg

**Comment by PieroCastillo** [comment]
mm, how SharpAudio localizes ffmpeg? 'cause installed using the path
![image](https://user-images.githubusercontent.com/39932324/111656472-8e98db00-87d8-11eb-9802-a27dcd55845f.png)

**Comment by PieroCastillo** [comment]
forget it, I've install FFmpeg full and it's fixed, thx u for ur help.
