### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by PieroCastillo** [feliwir/SharpAudio#19]
Hi, for me this lib is the best for .Net, but (for me) has an issue.
I don't know the reason, but SharpAudio has an high CPU usage problem.

this is the code:
```c#
static void Main(string[] args)
        {
            var  engine = AudioEngine.CreateDefault();
	    string path = "path"; //the song in mp3 file.

            if (engine == null)
            {
                Console.WriteLine("Failed to create an audio backend!");
            }

            if(!File.Exists(path))
            {
            Console.WriteLine("The file does not exist.");
	            return;
            }
            else
            {
            Console.WriteLine("The file exists.");
            }

            var  soundStream = new SoundStream(File.OpenRead(path), engine);
            soundStream.Volume = 10f;
            Console.WriteLine("Loaded Correctly");
            soundStream.Play();
        }
```

has this CPU usage:
![image](https://user-images.githubusercontent.com/39932324/111849061-bc664880-88da-11eb-9921-c9e1eb897f2a.png)

for example, MS Edge with 3 open tabs with youtube, uses a little of CPU (~5%)
![image](https://user-images.githubusercontent.com/39932324/111849657-203d4100-88dc-11eb-99ad-3f16da013915.png)

the lib with mp3 file uses the 10% to 16% of CPU, my CPU is an Ryzen 5600X, this is so high. (~1 core )

The lib is like that? or is there a solution?

**Comment by feliwir** [comment]
Sorry i didn't see this until now. I'll investigate later today

**Comment by feliwir** [comment]
I increased the **Sleep** duration from 2ms to 10ms. Not sure if this helps, will need to check on the next NuGet
