### ISSUE TITLE
Unable to play any mp3/wav files

### ISSUE THREAD

**Issue by feliwir** [feliwir/SharpAudio#2]
As mentioned by @jmacato in #1

**Comment by jmacato** [comment]
There are some mp3 files that it can't play and it outputs the ff exception:
```
Unhandled Exception: System.IO.InvalidDataException: Unknown format: ÿûàd
```

**Comment by feliwir** [comment]
Can you send me those files via mail (stephan.vedder@gmail.com) or attach them to this issue please? Thanks.

**Comment by jmacato** [comment]
Alright, also this is the FourCC code of the guilty file -> "255","251","224","100"

**Comment by feliwir** [comment]
Yeah, this is probably the issue. I am checking the FourCC here: https://github.com/feliwir/SharpAudio/blob/master/src/SharpAudio.Util/SoundStream.cs#L26

**Comment by jmacato** [comment]
@feliwir I've sent the file to your mail, please check it out

**Comment by jmacato** [comment]
i've overriden the switch case with `case "\u00FF\u00FB\u00E0\u0064":` and it worked somehow. Seems like MP3 has no consistent FourCC codes :/

**Comment by feliwir** [comment]
I changed the fourcc stuff to not use strings anymore. Will push in a bit
