### ISSUE TITLE
Allow OpenAL Soft (soft_oal.dll) on Windows

### ISSUE THREAD

**Issue by bntre** [feliwir/SharpAudio#5]
The Sample and Engine test work also with OpenAL Soft on Windows
(e.g. openal-soft-1.20.1-bin\bin\Win64\soft_oal.dll 
from https://openal-soft.org/openal-binaries/openal-soft-1.20.1-bin.zip).
So "soft_oal.dll" might be added to AlNative.cs near to "OpenAL32.dll".

**Comment by feliwir** [comment]
I'll add this, thanks

**Comment by feliwir** [comment]
Done in 4edfde51adc240c9345cd1b5bc50462f2650d05b
